package openaiclient

const (
	// ModelAda ...
	ModelAda = "ada"
	// ModelBabbage ...
	ModelBabbage = "babbage"
	// ModelCurie ...
	ModelCurie = "curie"
	// ModelDavinci ...
	ModelDavinci = "davinci"
)

// Text Models => https://platform.openai.com/docs/models/gpt-3
const (
	// ModelTextDavinci003 ...
	ModelTextDavinci003 = "text-davinci-003"
	// ModelTextDavinci002 ...
	ModelTextDavinci002 = "text-davinci-002"
	// ModelTextDavinci001 ...
	ModelTextDavinci001 = "text-davinci-001"
	// ModelTextCurie001 ...
	ModelTextCurie001 = "text-curie-001"
	// ModelTextBabbage001 ...
	ModelTextBabbage001 = "text-babbage-001"
	// ModelTextAda001 ...
	ModelTextAda001 = "text-ada-001"
)

// Codex => https://platform.openai.com/docs/models/codex
const (
	// ModelTextDavinci002 ...
	ModelCodeDavinci002 = "code-davinci-002"
	// ModelCodeCushman001 ...
	ModelCodeCushman001 = "code-cushman-001"
)

// MaxTokens ...
const MaxTokens = 4097
